/**
 * 시니어워크 - Mock 데이터
 * 시니어 특화 일자리 샘플 데이터
 */

export const CATEGORIES = [
  { id: 'cleaning', name: '청소/정리', icon: '🧹' },
  { id: 'delivery', name: '배달/운반', icon: '📦' },
  { id: 'guard', name: '경비/관리', icon: '🛡️' },
  { id: 'cooking', name: '조리/배식', icon: '🍳' },
  { id: 'care', name: '돌봄/간병', icon: '💊' },
  { id: 'parking', name: '주차관리', icon: '🅿️' },
  { id: 'tutoring', name: '교육/멘토', icon: '📚' },
  { id: 'errands', name: '심부름', icon: '🏃' },
];

export const JOBS = [
  {
    id: 'job1',
    title: '아파트 단지 내 청소 도우미',
    company: '래미안 관리사무소',
    companyIcon: '🏢',
    category: 'cleaning',
    location: '서울 강남구 역삼동',
    distance: 350,
    payAmount: 12000,
    payType: 'hourly',
    workDays: '주 3일 (월/수/금)',
    workTime: '오전 9시 ~ 12시',
    description: '아파트 단지 내 공용 공간 청소를 도와주실 분을 구합니다. 실내 청소 위주이며, 무거운 장비 사용은 없습니다.',
    requirements: ['건강한 체력', '성실하신 분'],
    benefits: ['교통비 지원', '간식 제공', '주차 가능'],
    postedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    isNew: true,
    isUrgent: false,
    applicants: 3,
    employer: {
      name: '김관리',
      mannerTemp: 38.2,
      avatar: '김',
    },
  },
  {
    id: 'job2',
    title: '학교 급식실 배식 보조',
    company: '역삼초등학교',
    companyIcon: '🏫',
    category: 'cooking',
    location: '서울 강남구 역삼동',
    distance: 580,
    payAmount: 65000,
    payType: 'daily',
    workDays: '주 5일 (월~금)',
    workTime: '오전 10시 ~ 오후 2시',
    description: '초등학교 급식실에서 배식을 도와주실 분을 찾습니다. 위생교육을 받으시면 바로 시작 가능합니다.',
    requirements: ['위생 관념이 철저하신 분', '오전 시간대 근무 가능하신 분'],
    benefits: ['점심 제공', '방학 중 휴무', '4대보험'],
    postedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    isNew: true,
    isUrgent: true,
    applicants: 7,
    employer: {
      name: '박영양',
      mannerTemp: 40.1,
      avatar: '박',
    },
  },
  {
    id: 'job3',
    title: '주차장 관리 요원',
    company: '강남빌딩 관리',
    companyIcon: '🏗️',
    category: 'parking',
    location: '서울 강남구 대치동',
    distance: 1200,
    payAmount: 2200000,
    payType: 'monthly',
    workDays: '주 5일',
    workTime: '오전 7시 ~ 오후 3시',
    description: '건물 지하 주차장 차량 안내 및 관리 업무입니다. 앉아서 쉬는 시간이 많아 체력 부담이 적습니다.',
    requirements: ['책임감 있으신 분', '기본적인 차량 상식'],
    benefits: ['중식 제공', '냉난방 완비', '경비실 제공'],
    postedAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    isNew: false,
    isUrgent: false,
    applicants: 12,
    employer: {
      name: '이건물',
      mannerTemp: 36.8,
      avatar: '이',
    },
  },
  {
    id: 'job4',
    title: '어르신 말벗 봉사 (유급)',
    company: '역삼동 복지관',
    companyIcon: '🏥',
    category: 'care',
    location: '서울 강남구 역삼동',
    distance: 280,
    payAmount: 30000,
    payType: 'per_task',
    workDays: '주 2~3일 선택',
    workTime: '오후 2시 ~ 4시',
    description: '혼자 사시는 어르신을 방문하여 대화를 나누는 말벗 서비스입니다. 따뜻한 마음을 가진 분이면 누구나 가능합니다.',
    requirements: ['대화를 즐기시는 분', '정기 방문 가능하신 분'],
    benefits: ['교통비 별도', '복지관 시설 이용 가능'],
    postedAt: new Date(Date.now() - 3 * 24 * 3600000).toISOString(),
    isNew: false,
    isUrgent: false,
    applicants: 5,
    employer: {
      name: '정복지',
      mannerTemp: 42.5,
      avatar: '정',
    },
  },
  {
    id: 'job5',
    title: '재활용 분리수거 도우미',
    company: '그린아파트 입주자대표회의',
    companyIcon: '♻️',
    category: 'cleaning',
    location: '서울 강남구 도곡동',
    distance: 900,
    payAmount: 11000,
    payType: 'hourly',
    workDays: '주 2일 (수/토)',
    workTime: '오전 8시 ~ 11시',
    description: '아파트 재활용 수거장에서 분리수거를 도와주실 분을 모집합니다.',
    requirements: ['기본 체력', '분리수거 상식'],
    benefits: ['간식 제공', '장갑/앞치마 지급'],
    postedAt: new Date(Date.now() - 6 * 3600000).toISOString(),
    isNew: true,
    isUrgent: false,
    applicants: 2,
    employer: {
      name: '최대표',
      mannerTemp: 37.5,
      avatar: '최',
    },
  },
  {
    id: 'job6',
    title: '아이 하교 후 돌봄 도우미',
    company: '개인 (맞벌이 가정)',
    companyIcon: '👨‍👩‍👧',
    category: 'care',
    location: '서울 강남구 역삼동',
    distance: 450,
    payAmount: 15000,
    payType: 'hourly',
    workDays: '주 5일 (월~금)',
    workTime: '오후 3시 ~ 6시',
    description: '초등학생 아이가 하교 후 집에서 안전하게 지낼 수 있도록 돌봐주실 분을 찾습니다. 간식 챙겨주시고 숙제 봐주시면 됩니다.',
    requirements: ['아이를 좋아하시는 분', '역삼동 인근 거주자'],
    benefits: ['간식비 별도', '아이 방학 시 협의'],
    postedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    isNew: false,
    isUrgent: true,
    applicants: 4,
    employer: {
      name: '한엄마',
      mannerTemp: 39.0,
      avatar: '한',
    },
  },
  {
    id: 'job7',
    title: '전통시장 반찬가게 보조',
    company: '엄마손 반찬',
    companyIcon: '🥘',
    category: 'cooking',
    location: '서울 강남구 개포동',
    distance: 1800,
    payAmount: 70000,
    payType: 'daily',
    workDays: '주 4일 (화~금)',
    workTime: '오전 6시 ~ 오후 1시',
    description: '전통시장 반찬가게에서 재료 손질과 포장을 도와주실 분을 구합니다. 요리 경험이 있으시면 환영합니다.',
    requirements: ['요리 경험 우대', '새벽 출근 가능하신 분'],
    benefits: ['반찬 제공', '시장 할인'],
    postedAt: new Date(Date.now() - 48 * 3600000).toISOString(),
    isNew: false,
    isUrgent: false,
    applicants: 8,
    employer: {
      name: '오사장',
      mannerTemp: 41.2,
      avatar: '오',
    },
  },
  {
    id: 'job8',
    title: '도서관 서가 정리 보조',
    company: '강남도서관',
    companyIcon: '📚',
    category: 'errands',
    location: '서울 강남구 삼성동',
    distance: 1500,
    payAmount: 10500,
    payType: 'hourly',
    workDays: '주 3일 선택',
    workTime: '오후 1시 ~ 5시',
    description: '도서관 서가 정리 및 도서 반납 처리를 도와주실 분을 구합니다. 조용한 환경에서 일하실 수 있습니다.',
    requirements: ['기본적인 한글 독해력', '꼼꼼하신 분'],
    benefits: ['도서 대출 우대', '냉난방 완비'],
    postedAt: new Date(Date.now() - 72 * 3600000).toISOString(),
    isNew: false,
    isUrgent: false,
    applicants: 6,
    employer: {
      name: '나관장',
      mannerTemp: 43.0,
      avatar: '나',
    },
  },
];

export const CHAT_ROOMS = [
  {
    id: 'chat1',
    jobId: 'job1',
    jobTitle: '아파트 단지 내 청소 도우미',
    otherUser: { name: '김관리', avatar: '김' },
    lastMessage: '네, 내일 오전 10시에 관리사무소로 오시면 됩니다.',
    lastMessageAt: new Date(Date.now() - 30 * 60000).toISOString(),
    unreadCount: 1,
    messages: [
      { id: 'm1', text: '안녕하세요! 청소 도우미 공고 보고 연락드립니다.', sender: 'me', time: new Date(Date.now() - 3600000).toISOString() },
      { id: 'm2', text: '안녕하세요! 관심 가져주셔서 감사합니다.', sender: 'other', time: new Date(Date.now() - 3500000).toISOString() },
      { id: 'm3', text: '혹시 면접은 어떻게 진행되나요?', sender: 'me', time: new Date(Date.now() - 3400000).toISOString() },
      { id: 'm4', text: '네, 내일 오전 10시에 관리사무소로 오시면 됩니다.', sender: 'other', time: new Date(Date.now() - 30 * 60000).toISOString() },
    ],
  },
  {
    id: 'chat2',
    jobId: 'job2',
    jobTitle: '학교 급식실 배식 보조',
    otherUser: { name: '박영양', avatar: '박' },
    lastMessage: '위생교육은 저희 학교에서 제공해드립니다!',
    lastMessageAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    unreadCount: 0,
    messages: [
      { id: 'm5', text: '급식실 보조 일자리에 지원합니다.', sender: 'me', time: new Date(Date.now() - 5 * 3600000).toISOString() },
      { id: 'm6', text: '감사합니다! 위생교육 받아보신 적 있으신가요?', sender: 'other', time: new Date(Date.now() - 4 * 3600000).toISOString() },
      { id: 'm7', text: '아직 받지 않았습니다. 따로 준비해야 할까요?', sender: 'me', time: new Date(Date.now() - 3 * 3600000).toISOString() },
      { id: 'm8', text: '위생교육은 저희 학교에서 제공해드립니다!', sender: 'other', time: new Date(Date.now() - 2 * 3600000).toISOString() },
    ],
  },
  {
    id: 'chat3',
    jobId: 'job4',
    jobTitle: '어르신 말벗 봉사 (유급)',
    otherUser: { name: '정복지', avatar: '정' },
    lastMessage: '다음 주 수요일부터 시작하시면 됩니다.',
    lastMessageAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    unreadCount: 3,
    messages: [
      { id: 'm9', text: '말벗 봉사에 관심이 있어 연락드립니다.', sender: 'me', time: new Date(Date.now() - 48 * 3600000).toISOString() },
      { id: 'm10', text: '반갑습니다! 혹시 봉사 경험이 있으신가요?', sender: 'other', time: new Date(Date.now() - 47 * 3600000).toISOString() },
      { id: 'm11', text: '네, 동네 복지관에서 1년 정도 했습니다.', sender: 'me', time: new Date(Date.now() - 46 * 3600000).toISOString() },
      { id: 'm12', text: '좋습니다! 간단한 면담 후 시작하시면 돼요.', sender: 'other', time: new Date(Date.now() - 25 * 3600000).toISOString() },
      { id: 'm13', text: '다음 주 수요일부터 시작하시면 됩니다.', sender: 'other', time: new Date(Date.now() - 24 * 3600000).toISOString() },
    ],
  },
];

export const USER_PROFILE = {
  name: '홍길동',
  age: 67,
  phone: '010-1234-5678',
  region: '서울 강남구 역삼동',
  skills: ['청소', '요리', '돌봄', '운전'],
  mannerTemp: 38.5,
  completedJobs: 12,
  reviewCount: 8,
  bio: '성실하게 일하겠습니다. 체력이 좋고 책임감이 강합니다.',
};
